<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SoportesProduccionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sql = <<<'SQL'
-- Script de migracion de Soportes para PostgreSQL

BEGIN;

DELETE FROM "soportes";

INSERT INTO "soportes" ("id", "codigo_barras", "numero_caso", "user_id", "cliente_id", "servicio", "estado", "equipo", "marca", "modelo", "serie", "nro_parte", "pieza_retirada", "pieza_serie", "pieza_falla", "piezas_retiradas_multiple", "piezas_adicionales_texto", "falla_equipo", "diagnostico", "falla_diagnostico_multiple", "perifericos", "precio", "pago", "deuda", "ingreso_fecha", "salida_fecha", "observaciones", "detalles_adicionales", "archivo_pdf", "activo", "atendido", "diagnostico_fin", "finalizado", "created_at", "updated_at") VALUES (16, 'KENYA250016', 'EZ-GT-250602-1137-HCO-RSHCO-A', 8, 20489498783, 'GARANTIA', 'E6', 'COMPUTADORA', 'KENYA', 'EZENT', 'EEB00124701137', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"titulo":"LA COMPUTADORA NO ENCIENDE","texto":"PLACA DEFECTUOSA: NS: S6M0PH348703JY6"}]', '{"cargador":"NO","cable_usb":"NO","cable_poder":"NO","sin_accesorios":"SI","otros":""}', 0, 666, 666, '2025-06-02 19:38:55', '2025-06-03 20:00:00', 'LA FALLA SE DIO POSTERIOR A DIAS DE LA ENTREGA DEL PRODUCTO.', 'AL REALIZAR EL CAMBIO DE PLACA LA COMPUTADORA EN CUESTION ENCENCIO SIN PROBLEMA ALGUNO - COMPONENTE DEFECTUOSO PLACA MADRE SE ENVIA A GARANTIA - DEL DISTRIBUIDOR', NULL, 'SI', 'NO', 'SI', 'NO', '2025-06-03 00:38:55', '2025-06-10 15:08:28');
INSERT INTO "soportes" ("id", "codigo_barras", "numero_caso", "user_id", "cliente_id", "servicio", "estado", "equipo", "marca", "modelo", "serie", "nro_parte", "pieza_retirada", "pieza_serie", "pieza_falla", "piezas_retiradas_multiple", "piezas_adicionales_texto", "falla_equipo", "diagnostico", "falla_diagnostico_multiple", "perifericos", "precio", "pago", "deuda", "ingreso_fecha", "salida_fecha", "observaciones", "detalles_adicionales", "archivo_pdf", "activo", "atendido", "diagnostico_fin", "finalizado", "created_at", "updated_at") VALUES (17, 'KENYA250017', 'EZ-GT-250602-1125-HCO-RSHCO-A', 8, 20489498783, 'SOPORTE', 'E6', 'COMPUTADORA', 'KENYA', 'EZENT', 'EEB00124701125', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"titulo":"LA COMPUTADORA NO ENCIENDE","texto":"PLACA DEFECTUOSA: NS: S6M0PH348629XJY"}]', '{"cargador":"NO","cable_usb":"NO","cable_poder":"NO","sin_accesorios":"SI","otros":""}', 0, 666, 666, '2025-06-10 10:07:58', '2025-06-10 20:00:00', 'EL EQUIPO FUE NO ENCENDIA DURANTE LA CONFORMIDAD DEL CLIENTE - DICHO FALLA FUE REPORTADOS A DIAS DE SER ENTREGADO.', 'SE PROCEDIO AL CAMBIO DE PLACA POSTERIROR A LAS PRUEBAS AREALIZADAS  YE L EQUIPO QUEDA OPERATIVO.  - DICHA PIEZA DEFECTUOSA ES GESTIONADO PARA SUE ENVIO A GARANTIA EN EL MAYORISTA ADQUIRIDO', NULL, 'SI', 'NO', 'SI', 'NO', '2025-06-10 15:07:58', '2025-06-10 15:08:59');
INSERT INTO "soportes" ("id", "codigo_barras", "numero_caso", "user_id", "cliente_id", "servicio", "estado", "equipo", "marca", "modelo", "serie", "nro_parte", "pieza_retirada", "pieza_serie", "pieza_falla", "piezas_retiradas_multiple", "piezas_adicionales_texto", "falla_equipo", "diagnostico", "falla_diagnostico_multiple", "perifericos", "precio", "pago", "deuda", "ingreso_fecha", "salida_fecha", "observaciones", "detalles_adicionales", "archivo_pdf", "activo", "atendido", "diagnostico_fin", "finalizado", "created_at", "updated_at") VALUES (18, 'KENYA250018', 'EZ-GT-2506271161-HCO-RDH-A', 8, 20489498783, 'SOPORTE', 'E6', 'COMPUTADORA', 'KENYA', 'EZENT-V1-MT', 'EEB00124701161', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"titulo":"DIAGNOSTICO","texto":"NO ENCIENDE"}]', '{"cargador":"NO","cable_usb":"NO","cable_poder":"NO","sin_accesorios":"NO","otros":"MANUAL, TECLADO Y MOUSE"}', 0, 0, 0, '2025-06-30 11:09:57', '2025-06-30 20:00:00', 'MB OBSEVADA NO ENCIENDE', 'LA MOTHERBORARD NO MUESTRA SEÑALES DE ENCENDIDO', NULL, 'SI', 'NO', 'SI', 'NO', '2025-06-30 16:09:57', '2025-07-26 14:05:45');
INSERT INTO "soportes" ("id", "codigo_barras", "numero_caso", "user_id", "cliente_id", "servicio", "estado", "equipo", "marca", "modelo", "serie", "nro_parte", "pieza_retirada", "pieza_serie", "pieza_falla", "piezas_retiradas_multiple", "piezas_adicionales_texto", "falla_equipo", "diagnostico", "falla_diagnostico_multiple", "perifericos", "precio", "pago", "deuda", "ingreso_fecha", "salida_fecha", "observaciones", "detalles_adicionales", "archivo_pdf", "activo", "atendido", "diagnostico_fin", "finalizado", "created_at", "updated_at") VALUES (19, 'KENYA250019', 'EZ-GT-2506271164-HCO-RDH-A', 8, 20489498783, 'SOPORTE', 'E6', 'COMPUTADORA', 'KENYA', 'EZENT-V1-MT', 'EEB00124701164', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"titulo":"DIAGNOSTICO","texto":"NO ENCIENDE"}]', '{"cargador":"NO","cable_usb":"NO","cable_poder":"NO","sin_accesorios":"NO","otros":"MANUAL, TECLADO Y MOUSE"}', 0, 0, 0, '2025-06-30 11:13:23', '2025-06-30 20:00:00', 'MB OBSEVADA NO ENCIENDE', 'LA MOTHERBORARD NO MUESTRA SEÑALES DE ENCENDIDO', NULL, 'SI', 'NO', 'SI', 'NO', '2025-06-30 16:13:23', '2025-07-26 14:05:31');
INSERT INTO "soportes" ("id", "codigo_barras", "numero_caso", "user_id", "cliente_id", "servicio", "estado", "equipo", "marca", "modelo", "serie", "nro_parte", "pieza_retirada", "pieza_serie", "pieza_falla", "piezas_retiradas_multiple", "piezas_adicionales_texto", "falla_equipo", "diagnostico", "falla_diagnostico_multiple", "perifericos", "precio", "pago", "deuda", "ingreso_fecha", "salida_fecha", "observaciones", "detalles_adicionales", "archivo_pdf", "activo", "atendido", "diagnostico_fin", "finalizado", "created_at", "updated_at") VALUES (20, 'KENYA250020', 'EZ-GT-250905-1237-HCO-RDS-A', 5, 20489498783, 'GARANTIA', 'E6', 'COMPUTADORA', 'KENYA', 'EZENT V1_MT', 'EGB00124701237', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"titulo":"Falla principal","texto":"EL EQUIPO AL ENCENDER EMITIO HUMO "}]', '{"cargador":"NO","cable_usb":"NO","cable_poder":"NO","sin_accesorios":"NO","otros":"MOUSE, CABLE DE PODER, TECLADO"}', 0, 0, 0, '2025-09-05 19:30:24', '2025-09-12 20:00:00', 'EL EQUIPO TENIA LA FUENTE QUEMADA', 'SE CAMBIO LA FUENTE DE PODER EQUIPO OPERATIUVO', NULL, 'NO', 'NO', 'SI', 'NO', '2025-09-06 00:30:24', '2025-09-16 20:57:33');
INSERT INTO "soportes" ("id", "codigo_barras", "numero_caso", "user_id", "cliente_id", "servicio", "estado", "equipo", "marca", "modelo", "serie", "nro_parte", "pieza_retirada", "pieza_serie", "pieza_falla", "piezas_retiradas_multiple", "piezas_adicionales_texto", "falla_equipo", "diagnostico", "falla_diagnostico_multiple", "perifericos", "precio", "pago", "deuda", "ingreso_fecha", "salida_fecha", "observaciones", "detalles_adicionales", "archivo_pdf", "activo", "atendido", "diagnostico_fin", "finalizado", "created_at", "updated_at") VALUES (21, 'KENYA250021', 'OZ-ST-250925-LIM-ONPE-A', 9, 20291973851, 'SOPORTE', 'E6', 'COMPUTADORA', 'KENYA', 'S331', 'OS221021000664', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"titulo":"Falla principal","texto":"reinicios"}]', '{"cargador":"NO","cable_usb":"NO","cable_poder":"NO","sin_accesorios":"NO","otros":"mouse,teclado,cable de poder"}', 0, 0, 0, '2025-09-30 11:35:58', '2025-10-02 03:00:00', 'EL EQUIPO PRESENTA REINCIOS CAUSA DEL SSD M.2', 'EL EQUIPO SE REINICIA CONSTANTEMENTE , SE PROCEDIO CON EL CAMBIO DEL M.2 PARA EVITAR LOS REINICIOS', NULL, 'SI', 'NO', 'SI', 'NO', '2025-09-30 16:35:58', '2025-12-01 20:42:38');
INSERT INTO "soportes" ("id", "codigo_barras", "numero_caso", "user_id", "cliente_id", "servicio", "estado", "equipo", "marca", "modelo", "serie", "nro_parte", "pieza_retirada", "pieza_serie", "pieza_falla", "piezas_retiradas_multiple", "piezas_adicionales_texto", "falla_equipo", "diagnostico", "falla_diagnostico_multiple", "perifericos", "precio", "pago", "deuda", "ingreso_fecha", "salida_fecha", "observaciones", "detalles_adicionales", "archivo_pdf", "activo", "atendido", "diagnostico_fin", "finalizado", "created_at", "updated_at") VALUES (22, 'KENYA260022', 'EL60001', 9, 20159855938, 'GARANTIA', 'E5', 'COMPUTADORA', 'KENYA', 'EZENT V1-MT', 'EHB00014801258', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[{"titulo":"Falla principal","texto":"PROBLEMAS DE ENCENDIDO  Y PERIFERICOS"}]', '{"cargador":"","cable_usb":"","cable_poder":"SI","sin_accesorios":"NO","otros":"MOUSE,TECLADO,TARJETA DE RED"}', 0, 1600, 1600, '2026-01-13 10:12:20', '2026-01-13 20:00:00', 'MB OBSEVADA PROBLEMAS EN LOS PERIFERICOS Y EN EL ENCENDIDO', 'LA PLACA MADRE PRESENTA FALLO , LO QUE IMPIDE EL FUNCIONAMIENTO ESTABLE DEL SISTEMA.', '/storage/pdfs/soporte_1768859583_2RUobhnwdd.pdf', 'SI', 'NO', 'SI', 'NO', '2026-01-13 15:12:20', '2026-01-22 16:01:56');
INSERT INTO "soportes" ("id", "codigo_barras", "numero_caso", "user_id", "cliente_id", "servicio", "estado", "equipo", "marca", "modelo", "serie", "nro_parte", "pieza_retirada", "pieza_serie", "pieza_falla", "piezas_retiradas_multiple", "piezas_adicionales_texto", "falla_equipo", "diagnostico", "falla_diagnostico_multiple", "perifericos", "precio", "pago", "deuda", "ingreso_fecha", "salida_fecha", "observaciones", "detalles_adicionales", "archivo_pdf", "activo", "atendido", "diagnostico_fin", "finalizado", "created_at", "updated_at") VALUES (24, 'VASCO260024', 'PL60002', 1, 20169004359, 'GARANTIA', 'E5', 'ESTACION DE TRABAJO', 'KENYA', 'WS70', 'PLB00009201351', 'NULL', 'NULL', 'NULL', 'NULL', '"[{\"nombre\":\"\",\"serie\":\"\",\"falla\":\"\"}]"', NULL, 'REINICIOS', 'CAMBIO DE FUENTE', '[{"titulo":"Falla principal","texto":"rEINICIOS "}]', '{"cargador":"","cable_usb":"","cable_poder":"NO","sin_accesorios":"NO","otros":""}', 0, 260, 260, '2026-01-22 16:48:45', '2026-01-22 02:00:00', 'EL EQUIPO SE REINICIABA , DESPUES DEL ENCENDIDO DEL PROGRAMA COMO EXCEL O PROGRAMAS ESPECIFICOS , SE PROCEDIO AL CAMBIO DE FUENTE DE PODER , TERMINANDO DE  INSTALAR EL PSU NO PRESENTO PROBLEMAS DE REINICIO , DEJANDO EL EQUIPO EN OPTIMAS CONDISIONES', 'EL EQUIPO SE REINICIABA , DESPUES DEL ENCENDIDO DEL PROGRAMA COMO EXCEL O PROGRAMAS ESPECIFICOS , SE PROCEDIO AL CAMBIO DE FUENTE DE PODER , DESPUES DE   INSTALAR EL PSU NO PRESENTO PROBLEMAS DE REINICIO , DEJANDO EL EQUIPO EN OPTIMAS CONDISIONES  , PERO SE LE SUGIRIO REINSTALAR SUS PROGRAMA', '/storage/pdfs/soporte_1769118525_oqt3QTPNBJ.pdf', 'SI', 'NO', 'SI', 'NO', '2026-01-22 21:48:46', '2026-02-01 00:22:02');
INSERT INTO "soportes" ("id", "codigo_barras", "numero_caso", "user_id", "cliente_id", "servicio", "estado", "equipo", "marca", "modelo", "serie", "nro_parte", "pieza_retirada", "pieza_serie", "pieza_falla", "piezas_retiradas_multiple", "piezas_adicionales_texto", "falla_equipo", "diagnostico", "falla_diagnostico_multiple", "perifericos", "precio", "pago", "deuda", "ingreso_fecha", "salida_fecha", "observaciones", "detalles_adicionales", "archivo_pdf", "activo", "atendido", "diagnostico_fin", "finalizado", "created_at", "updated_at") VALUES (25, 'KENYA260025', 'GL60003', 9, 20527141762, 'GARANTIA', 'E5', 'COMPUTADORA', 'KENYA', 'GENWORK DT90', 'GLA00074701020', 'GC721WDU0B430S', 'NULL', 'NULL', 'NULL', '"[{\"nombre\":\"PSU TT 450W\",\"serie\":\"219\",\"falla\":\"NO ENERGIZA\"}]"', NULL, 'PC NO PRENDE', 'PSU MAL ESTADO', '[{"titulo":"Falla principal","texto":""}]', '{"cargador":"","cable_usb":"","cable_poder":"NO","sin_accesorios":"NO","otros":""}', 0, 0, 0, '2026-02-05 15:42:42', '2026-02-05 20:00:00', 'CAMBIO PSU', 'PSU NO ENERGIZA, SE PROCEDIO A REEMPLAZAR POR UNO NUEVO., PC QUEDO OPERATIVA', '/storage/pdfs/soporte_1770324162_TJoSvOCKiF.pdf', 'NO', 'NO', 'SI', 'NO', '2026-02-05 20:42:42', '2026-02-05 20:45:19');
INSERT INTO "soportes" ("id", "codigo_barras", "numero_caso", "user_id", "cliente_id", "servicio", "estado", "equipo", "marca", "modelo", "serie", "nro_parte", "pieza_retirada", "pieza_serie", "pieza_falla", "piezas_retiradas_multiple", "piezas_adicionales_texto", "falla_equipo", "diagnostico", "falla_diagnostico_multiple", "perifericos", "precio", "pago", "deuda", "ingreso_fecha", "salida_fecha", "observaciones", "detalles_adicionales", "archivo_pdf", "activo", "atendido", "diagnostico_fin", "finalizado", "created_at", "updated_at") VALUES (26, 'KENYA260026', 'pL60004', 9, 20131365994, 'GARANTIA', 'E5', 'ESTACION DE TRABAJO', 'KENYA', 'PROWORK WS90', 'PKB00016001345', 'P9CTSDOWNHPXO3ZOPV16', 'NULL', 'NULL', 'NULL', '"[{\"nombre\":\"PSU G850 80 PLUS GOL\",\"serie\":\"0237\",\"falla\":\"NO ENERGIZA\"}]"', NULL, 'NO ENCIENDE', 'CAMBIO DE FUENTE', '[{"titulo":"Falla principal","texto":""}]', '{"cargador":"","cable_usb":"","cable_poder":"NO","sin_accesorios":"NO","otros":""}', 0, 0, 0, '2026-02-18 15:34:35', '2026-02-18 20:00:00', 'SE REALIZÓ EL REEMPLAZO DE LA FUENTE DE PODER  G85O 80 PLUS GOLD DEBIDO A UNA FALLA TÉCNICA EN LA UNIDAD ORIGINAL', 'PSU NO ENERGIZABA LA PLACA BASE NI LOS COMPONENTES PERIFÉRICOS (FALLA DE SALIDA DE CORRIENTE).; SE REALIZO CAMBIO DE PSU', '/storage/pdfs/soporte_1771447563_vxyZOiT3rW.pdf', 'NO', 'NO', 'SI', 'NO', '2026-02-18 20:34:35', '2026-02-18 21:20:56');
INSERT INTO "soportes" ("id", "codigo_barras", "numero_caso", "user_id", "cliente_id", "servicio", "estado", "equipo", "marca", "modelo", "serie", "nro_parte", "pieza_retirada", "pieza_serie", "pieza_falla", "piezas_retiradas_multiple", "piezas_adicionales_texto", "falla_equipo", "diagnostico", "falla_diagnostico_multiple", "perifericos", "precio", "pago", "deuda", "ingreso_fecha", "salida_fecha", "observaciones", "detalles_adicionales", "archivo_pdf", "activo", "atendido", "diagnostico_fin", "finalizado", "created_at", "updated_at") VALUES (28, 'KENYA260028', 'GL60005', 9, 20556272535, 'SOPORTE', 'E5', 'COMPUTADORA', 'KENYA', 'GENWORK WS90', 'GLB00078801556', 'P9CTSDOWNHPXO3ZOPV16', 'NULL', 'NULL', 'NULL', '"[{\"nombre\":\"\",\"serie\":\"\",\"falla\":\"\"}]"', NULL, 'REINICIOS CONSTANTES', 'ACTUALIZACION DE BIOS', '[{"titulo":"Falla principal","texto":""}]', '{"cargador":"","cable_usb":"","cable_poder":"NO","sin_accesorios":"NO","otros":""}', 0, 0, 0, '2026-02-23 09:37:37', '2026-02-23 20:00:00', 'AL CLIENTE LE NOTIFICABA QUE NO DETECTABA EL LIQUIDO REFRIGERANTE', 'SE PROCEDIO A HACER UNA REVISION DE BIOS, CUAL  SE NOTIFICO QUE NECESITABA UNA ACTUALIZACION RECIENTE.  CON LA ACTUALIZACION , EL EQUIPO VOLVIO A TRABAJAR NORMALMENTE', '/storage/pdfs/soporte_1771857905_Kz4m2Dq73D.pdf', 'NO', 'NO', 'SI', 'NO', '2026-02-23 14:37:37', '2026-02-23 14:45:06');
INSERT INTO "soportes" ("id", "codigo_barras", "numero_caso", "user_id", "cliente_id", "servicio", "estado", "equipo", "marca", "modelo", "serie", "nro_parte", "pieza_retirada", "pieza_serie", "pieza_falla", "piezas_retiradas_multiple", "piezas_adicionales_texto", "falla_equipo", "diagnostico", "falla_diagnostico_multiple", "perifericos", "precio", "pago", "deuda", "ingreso_fecha", "salida_fecha", "observaciones", "detalles_adicionales", "archivo_pdf", "activo", "atendido", "diagnostico_fin", "finalizado", "created_at", "updated_at") VALUES (29, 'VASCO260029', 'pL60004', 9, 20600125816, 'SOPORTE', 'E5', 'ESTACION DE TRABAJO', 'KENYA', 'PROWORK WS90', 'PLB00010901596', 'NULL', 'NULL', 'NULL', 'NULL', '"[{\"nombre\":\"\",\"serie\":\"\",\"falla\":\"\"}]"', NULL, 'TEMPERATURAS ALTAS EN APLICACIONES', 'MANTENIMIENTO DEL SISTEMA DE REFRIGERACION', '[{"titulo":"Falla principal","texto":""}]', '{"cargador":"","cable_usb":"","cable_poder":"NO","sin_accesorios":"NO","otros":""}', 0, 0, 0, '2026-02-23 14:46:11', '2026-02-24 20:00:00', 'TEMPERATURA ALTA EN EL PROCESADOR EN ESTADO DE REPOSO Y EXIGIDO', 'SE PROCEDIO  A REALIZAR EL MANTENIMIENTO DEL REFRIGERACION LIQUIDA  Y CAMBIO DE PASTA TERMICA  CON ELLO BAJO LOS GRADOS DE TEMPERATURA A SUS ESTADOS NORMALES.', '/storage/pdfs/soporte_1771960251_jUvX8v2U7X.pdf', 'NO', 'NO', 'SI', 'NO', '2026-02-23 19:46:11', '2026-02-24 19:10:52');

SELECT setval('soportes_id_seq', COALESCE((SELECT MAX(id)+1 FROM "soportes"), 1), false);

COMMIT;
SQL;
        DB::unprepared($sql);
        $this->command->info('Datos de soportes insertados exitosamente en PostgreSQL.');
    }
}
